apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: namespace-mutator
webhooks:
- name: namespace-mutator.sedooe.com
  failurePolicy: Fail
  clientConfig:
    #      service:
    #        name: sidecar-injector-webhook-svc
    #        namespace: default
    #        path: "/mutate"
    url: https://0149e835.ngrok.io/mutate
    caBundle: ""
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - namespaces
