apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: namespace-validator
webhooks:
- name: namespace-validator.sedooe.com
  failurePolicy: Fail
  clientConfig:
    #      service:
    #        name: sidecar-injector-webhook-svc
    #        namespace: default
    #        path: "/validate"
    url: https://0149e835.ngrok.io/validate
    caBundle: ""
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - namespaces
